# Generated by Django 4.2.13 on 2024-05-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('timestamps_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='util.timestamps')),
                ('text', models.CharField(max_length=500)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.list')),
            ],
            bases=('util.timestamps', models.Model),
        ),
    ]
